# ============================================================================
# Host 2 — Management Server (ThinkStation)
#
# Role / Management Plane: UniFi Controller + central Observability stack.
# Sits behind Host 1 (edge-router) as a plain LAN client, reaching the router
# at 192.168.99.1. Prometheus here scrapes BOTH its own node_exporter and the
# edge-router's node_exporter (192.168.99.1:9100); Grafana is provisioned to
# use this local Prometheus as its default datasource.
# ============================================================================

{ pkgs, ... }:

let
  gw = "192.168.99.1";
in
{
  imports = [ ./hardware-configuration.nix ];

  # ── Identity ─────────────────────────────────────────────────────────────
  system.stateVersion = "26.05";
  networking.hostName = "mgmt";

  # ── Network state ─────────────────────────────────────────────────────────
  networking.useDHCP = false;
  networking.interfaces.enp3s0 = {          # *** adjust to your NIC (`ip link`) ***
    useDHCP = false;
    ipv4.addresses = [{
      address = "192.168.99.10";            # static LAN client (== network.id spec)
      prefixLength = 24;
    }];
  };
  # Router is the default gateway + upstream DNS (kept resolvable even if
  # Unbound is briefly down).
  networking.defaultGateway = gw;
  networking.nameservers = [ gw ];

  # ── Firewall ─────────────────────────────────────────────────────────────
  networking.firewall.enable = true;
  networking.firewall.allowedTCPPorts = [
    22                           # SSH
    3000                         # Grafana web UI (bound to the LAN NIC below)
    8443                         # UniFi web UI
  ];
  networking.firewall.allowedUDPPorts = [
    10001                        # UniFi AP discovery/inform
  ];

  # ── UniFi Controller ──────────────────────────────────────────────────────
  # MongoDB ships in the unfree channel — it must be allowed for `unifi` to
  # build. openFirewall adds UniFi's full port set (8080 inform, 8443 UI,
  # 6789 throughput, 10001 broadcast) on top of our explicit list above.
  nixpkgs.config.allowUnfree = true;
  services.unifi = {
    enable = true;
    openFirewall = true;
  };

  # ── Prometheus (central scraper) ─────────────────────────────────────────
  services.prometheus = {
    enable = true;
    listenAddress = "192.168.99.10";       # LAN-bound
    port = 9090;
    extraFlags = [ "--web.enable-lifecycle" ];
    exporters = {
      node = {
        enable = true;                      # scrape ourselves
        enabledCollectors = [ "systemd" ];
      };
    };
    scrapeConfigs = [
      {
        job_name = "management";
        static_configs = [{ targets = [ "192.168.99.10:9100" ]; }];
      }
      {
        job_name = "edge-router";
        static_configs = [{ targets = [ "${gw}:9100" ]; }];   # Host 1
      }
    ];
  };

  # ── Grafana (LAN-bound, auto-provisioned to local Prometheus) ─────────────
  services.grafana = {
    enable = true;
    settings = {
      server = {
        domain = "192.168.99.10";
        http_addr = "192.168.99.10";
        http_port = 3000;
        root_url = "http://192.168.99.10:3000";
      };
      "auth.anonymous".enabled = false;      # no anonymous access (was true in the draft)
      "auth.basic".enabled = true;
      # Grafana's `secret_key` and `admin_password` have no defaults since
      # 25.11 — read them from files instead of the Nix store (see grafana
      # docs on file-provider). Files are generated by grafana-secret on
      # first boot; admin password is printed to the journal once.
      security.secret_key = "$__file{/etc/grafana/secret_key}";
      security.admin_password = "$__file{/etc/grafana/admin_password}";
    };
    provision = {
      enable = true;
      datasources.settings.datasources = [
        {
          name = "Prometheus";
          type = "prometheus";
          access = "proxy";
          url = "http://localhost:9090";
          isDefault = true;
        }
      ];
    };
  };

  # ── Management access + user ──────────────────────────────────────────────
  # Password auth disabled (keys only) — mirrors the edge router. `drn` still
  # has a console password (`initialPassword` below) for local login.
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = false;
      PubkeyAuthentication = true;
    };
    startWhenNeeded = true;
  };

  # Grafana needs real secret_key/admin_password files (see security.* above).
  # Generate them idempotently on first boot, before grafana starts. The admin
  # password is random and printed to the journal once: `journalctl -u grafana-secret`.
  systemd.services.grafana-secret = {
    description = "Generate Grafana secrets (secret_key, admin_password) if absent";
    before = [ "grafana.service" ];
    wantedBy = [ "multi-user.target" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.bash}/bin/bash -c 'install -d -o grafana -g grafana -m 750 /etc/grafana; [ -s /etc/grafana/secret_key ] || ${pkgs.openssl}/bin/openssl rand -hex 32 > /etc/grafana/secret_key; if [ ! -s /etc/grafana/admin_password ]; then ${pkgs.openssl}/bin/openssl rand -hex 12 > /etc/grafana/admin_password; echo \"Grafana admin password: $(cat /etc/grafana/admin_password)\" >&2; fi; chown -R grafana:grafana /etc/grafana; chmod 640 /etc/grafana/secret_key /etc/grafana/admin_password'";
    };
  };
  users.users.drn = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    initialPassword = "changeme";
    openssh.authorizedKeys.keys = [
      # dev machine (darrenmeehan@fedora)
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK5LOFpTvGdlomaMjY33qWhvybAVYJLZ9efU6wny2NUq hi@drn.ie"
      # ops (home-k8s, same key the app-node workflow uses)
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHSmchQ7JS1UcyBy2lMoYuBQs/6H/VgqB+TrArRE6QDW home-k8s"
    ];
  };

  environment.systemPackages = with pkgs; [ vim curl git ripgrep ];
}